UrbanDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from task2.views import Index, index
from task5.views import sign_up_by_html, sign_up_by_django

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', index, name='index'),
    path('', sign_up_by_html, name='sign_up_by_html'),
    path('django_sign_up/', sign_up_by_django, name='sign_up_by_django'),
    path('index/', include('task3.urls', namespace='task3')),
    path('platform/', include('task4.urls', namespace='task4')),
    path('index/', Index.as_view(), name='index2'),
]

task3/urls.py
from django.urls import path
from task3.views import Main, Shop, Basket

app_name = 'task3'

urlpatterns = [
    path('platform/', Main.as_view(), name='platform'),
    path('shop/', Shop.as_view(), name='shop'),
    path('basket/', Basket.as_view(), name='basket'),
]

task4/urls.py
from django.urls import path
from task4.views import Main, Shop, Basket

app_name = 'task4'

urlpatterns = [
    path('', Main.as_view(), name='platform'),
    path('shop/', Shop.as_view(), name='shop'),
    path('basket/', Basket.as_view(), name='basket'),
]

task5/models.py
from django.db import models

# Create your models here.

task5/forms.py
from django import forms


class UserRegister(forms.Form):
    username = forms.CharField(label='Введите логин', max_length=30, required=True)
    password = forms.CharField(label='Введите пароль', min_length=8, required=True)
    repeat_password = forms.CharField(label='Повторите пароль', min_length=8, required=True)
    age = forms.IntegerField(label='Введите свой возраст', max_value=130, required=True)

example1/views.py
from django.shortcuts import render


# Create your views here.
# def index(request):
#     return render(request, 'index.html')

example2/views.py
from django.shortcuts import render

# Create your views here.

example3/views.py
from django.shortcuts import render

# Create your views here.

task2/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'second_task/class_template.html'


# Create your views here.
def index(request):
    return render(request, 'second_task/func_template.html')

task3/views.py
from django.views.generic import TemplateView


class BaseView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_page'] = 'Главная страница'
        context['main'] = 'Главная'
        context['shop'] = 'Магазин'
        context['basket'] = 'Корзина'
        context['games'] = 'Игры'
        context['game_1'] = 'Atomic Heart'
        context['game_2'] = 'Cyberpunk 2077'
        context['game_3'] = 'PayDay 2'
        context['buy_button'] = 'Купить'
        context['back_button'] = 'Вернуться обратно'
        context['basket_message'] = 'Извините, ваша корзина пуста!'
        return context


class Main(BaseView):
    template_name = 'third_task/main_page_template.html'


class Shop(BaseView):
    template_name = 'third_task/shop_template.html'


class Basket(BaseView):
    template_name = 'third_task/basket_template.html'

task4/views.py
from django.views.generic import TemplateView


class BaseView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_page'] = 'Главная страница'
        context['main'] = 'Главная'
        context['shop'] = 'Магазин'
        context['basket'] = 'Корзина'
        context['games'] = 'Игры'
        context['game_list'] = ['Atomic Heart', 'Cyberpunk 2077', 'PayDay 2']
        context['buy_button'] = 'Купить'
        context['back_button'] = 'Вернуться обратно'
        context['basket_message'] = 'Извините, ваша корзина пуста!'
        return context


class Main(BaseView):
    template_name = 'fourth_task/main_page_template.html'


class Shop(BaseView):
    template_name = 'fourth_task/shop_template.html'


class Basket(BaseView):
    template_name = 'fourth_task/basket_template.html'

task5/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template.defaultfilters import title

from task5.forms import UserRegister

users = ['John', 'Jack', 'User', 'Maike']


def sign_up_by_html(request):
    info = {}
    if request.method == "POST":
        info['username'] = username = request.POST['username']
        info['password'] = password = request.POST['password']
        info['repeat_password'] = repeat_password = request.POST['repeat_password']
        info['age'] = age = request.POST['age']

        if password != repeat_password:
            info['error'] = 'Пароли не совпадают!'
        elif int(age) < 18:
            info['error'] = 'Вы должны быть старше 18!'
        elif title(username) in users:
            info['error'] = 'Пользователь уже существует!'
        else:
            users.append(title(username))
            info['success_message'] = f'Приветствуем,  {username}!'

        return render(request, 'fifth_task/registration_page.html', context=info)

    return render(request, 'fifth_task/registration_page.html')

def sign_up_by_django(request):
    info = {}
    if request.method == "POST":
        form = UserRegister(request.POST)
        if form.is_valid():
            info['username'] = username = form.cleaned_data['username']
            info['password'] = password = form.cleaned_data['password']
            info['repeat_password'] = repeat_password = form.cleaned_data['repeat_password']
            info['age'] = age = form.cleaned_data['age']

            if password != repeat_password:
                info['error'] = 'Пароли не совпадают!'
            elif int(age) < 18:
                info['error'] = 'Вы должны быть старше 18!'
            elif title(username) in users:
                info['error'] = 'Пользователь уже существует!'
            else:
                users.append(title(username))
                info['success_message'] = f'Приветствуем,  {username}!'

            return render(request, 'fifth_task/registration_page.html', context=info)
    else:
        form = UserRegister(request.POST)
        return render(request, 'fifth_task/registration_page.html', {'form': form})

templates/fifth_task/registration_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
    <p> {{ error }} </p>
    <form method="post" style="margin: 10px;">
        {% csrf_token %}
        <label for="username">Введите логин</label>
        <input type="text" id="username" name="username" maxlength="30" value="{{ username }}" required>

        <label for="password">Введите пароль</label>
        <input type="text" id="password" name="password" minlength="8" value="{{ password }}" required>

        <label for="repeat_password">Повторите пароль</label>
        <input type="text" id="repeat_password " name="repeat_password" minlength="8" value="{{ repeat_password }}" required>

        <label for="age">Введите свой возраст</label>
        <input type="number" id="age" name="age" max="130" value="{{ age }}" required>

        <button type="submit">Зарегистрироваться</button>
    </form>
    <h2 style="text-align: center;">{{ success_message }}</h2>
</body>
</html>

templates/fourth_task/basket_template.html
{% extends 'fourth_task\menu.html' %}

{% block pagename %}
    <div>
        <h1 style="margin-left: 40px;">{{ basket }}</h1>
    </div>
{% endblock %}

{% block menu %}
  {{ block.super }}
{% endblock %}

{% block content %}
    <div>
        <h1 style="margin-left: 40px;">{{ basket_message }}</h1>
    </div>
{% endblock %}

templates/fourth_task/main_page_template.html
{% extends "fourth_task\menu.html" %}

{% block pagename %}
  {{ block.super }}
{% endblock %}

{% block menu %}
  {{ block.super }}
{% endblock %}

{% block content %}
  {{ block.super }}
{% endblock %}

templates/fourth_task/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block pagename %}
    <div>
        <h1 style="padding-left: 2em;">{{ main_page }}</h1>
    </div>
    {% endblock %}
    {% block menu %}
    <div>
        <a href="{% url 'task4:platform' %}"><h3 style="padding-left: 4em;">{{ main }}</h3></a>
    </div>
    <div>
        <a href="{% url 'task4:shop' %}"><h3 style="padding-left: 4em;">{{ shop }}</h3></a>
    </div>
    <div>
        <a href="{% url 'task4:basket' %}"><h3 style="padding-left: 4em;">{{ basket }}</h3></a>
    </div>
    {% endblock %}

    {% block content %}

    {% endblock %}
</body>
</html>

templates/fourth_task/shop_template.html
{% extends 'fourth_task\menu.html' %}

{% block pagename %}
  <div>
      <h1 style="margin-left: 42px;">{{ games }}</h1>
  </div>
{% endblock %}

{% block menu %}
  {{ block.super }}
{% endblock %}

{% block content %}
    <Ul style="padding-left: 4em;">
        {% for i in game_list %}
        <li>
            <p>
                <h3 style="display: inline;">{{ i }}</h3>
                <button style="display: inline;">{{ buy_button }}</button>
            <p>
        </li>
        {% endfor %}
    </Ul>
{% endblock %}

templates/second_task/class_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div style="text-align: center;">
        <h1>Это шаблон для классового представления</h1>
    </div>
    <div style="text-align: center;">
        <button style="margin-left: 20px;">
            <a href="{% url 'task3:platform' %}"><h3>Перейти на страницу платформы</h3></a>
        </button>
    </div>
</body>
</html>

templates/second_task/func_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div style="text-align: center;">
        <h1>Это шаблон для функционального представления</h1>
    </div>
    <div style="text-align: center;">
        <button style="margin-left: 20px;">
            <a href="{% url 'task4:platform' %}"><h3>Перейти на страницу платформы</h3></a>
        </button>
    </div>
</body>
</html>

templates/third_task/basket_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Games</title>
</head>
<body>
    <div>
        <h1 style="margin-left: 40px;">{{ basket_message }}</h1>
    </div>
    <button style="margin-left: 40px;">
        <a href="{% url 'task3:platform' %}"><h3>{{ back_button }}</h3></a>
    </button>
</body>
</html>

templates/third_task/main_page_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <div>
    <h1 style="padding-left: 2em;">{{ main_page }}</h1>
  </div>
  <div>
    <a href="{% url 'task3:platform' %}"><h3 style="padding-left: 4em;">{{ main }}</h3></a>
  </div>
  <div>
    <a href="{% url 'task3:shop' %}"><h3 style="padding-left: 4em;">{{ shop }}</h3></a>
  </div>
  <div>
    <a href="{% url 'task3:basket' %}"><h3 style="padding-left: 4em;">{{ basket }}</h3></a>
  </div>
</body>
</html>

templates/third_task/shop_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Games</title>
</head>
<body>
    <div>
        <h1 style="margin-left: 42px;">{{ games }}</h1>
    </div>
    <Ul style="padding-left: 4em;">
        <li>
            <p>
                <h3 style="display: inline;">{{ game_1 }}</h3>
                <button style="display: inline;">{{ buy_button }}</button>
            <p>
        </li>
        <li>
            <p>
                <h3 style="display: inline;">{{ game_2 }}</h3>
                <button style="display: inline;">{{ buy_button }}</button>
            <p>
        </li>
        <li>
            <p>
                <h3 style="display: inline;">{{ game_3 }}</h3>
                <button style="display: inline;">{{ buy_button }}</button>
            <p>
        </li>
    </Ul>
    <button style="margin-left: 40px;">
        <a href="{% url 'task3:platform' %}"><h3>{{ back_button }}</h3></a>
    </button>
</body>
</html>